/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.codez.projectdash;

import static com.codez.projectdash.FormMotor.jTableMot;
import java.sql.Connection;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ezz
 */
public class Transaksi extends javax.swing.JFrame {

    /**
     * Creates new form Transaksi
     */
    
    
    
    public Transaksi() {
        initComponents();
        jLabelStokUnit.setVisible(false);
        jLabelStokUnitKur.setVisible(false);
        jLabelStatus.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    public void insertTrans(){
        try {
            String sql = "INSERT INTO tb_transaksi VALUES ('" + jTfIdTrans.getText() + "', '" + jLabelIdMot.getText() + "', '" + jLabelIdCust.getText() + "', '" + jLabelJenisMot.getText() + "', '" + jLabelTipeMot.getText() + "', '" + jLabelStokUnitKur.getText() + "', '" + jlLabelNamaCust.getText() + "', '" + jLabelAlamatCust.getText() + "', '" + jLabelNoHpCust.getText() + "', '" + jLabelTotalHarga.getText() + "', '" + jLabelStatus.getText() + "')";
            java.sql.Connection con = (Connection)ConnectionDB.configDB();
            java.sql.PreparedStatement pst = con.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(null, "Data Transaksi Berhasi Diinput");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Data Gagal Diinput" + e.getMessage());
        }
    }
    
    public void updateStokTransTable(){
        try {
            String sql = "UPDATE tb_transaksi SET Jumlah_UnitTrans = '" + jLabelStokUnitKur.getText() + "' WHERE ID_Motor = '" + jLabelIdMot.getText() + "'";
            java.sql.Connection con = (Connection)ConnectionDB.configDB();
            java.sql.PreparedStatement pst = con.prepareStatement(sql);
            pst.execute();
        } catch (Exception e) {
        }
             
   
    }
    
    public void updateStok(){
        try {
            String sql = "UPDATE tb_motor SET Jumlah_Unit = '" + jLabelStokUnitKur.getText() + "' WHERE ID_Motor = '" + jLabelIdMot.getText() + "'";
            java.sql.Connection conn = (Connection)ConnectionDB.configDB();
            java.sql.PreparedStatement pst = conn.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(null, "Jumlah Stok Unit Berhasil Diupdate");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        
    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        idMot = new javax.swing.JLabel();
        jLabelIdMot = new javax.swing.JLabel();
        garis = new javax.swing.JLabel();
        jenisMot = new javax.swing.JLabel();
        jLabelJenisMot = new javax.swing.JLabel();
        garis1 = new javax.swing.JLabel();
        tipeMot = new javax.swing.JLabel();
        jLabelTipeMot = new javax.swing.JLabel();
        garis2 = new javax.swing.JLabel();
        warnaMot = new javax.swing.JLabel();
        jLabelWarnaMot = new javax.swing.JLabel();
        garis3 = new javax.swing.JLabel();
        hargaMot = new javax.swing.JLabel();
        jLabelHargaMot = new javax.swing.JLabel();
        garis4 = new javax.swing.JLabel();
        jLabelStokUnit = new javax.swing.JLabel();
        jLabelStokUnitKur = new javax.swing.JLabel();
        jLabelStatus = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        idCust = new javax.swing.JLabel();
        jLabelIdCust = new javax.swing.JLabel();
        garis5 = new javax.swing.JLabel();
        namaCust = new javax.swing.JLabel();
        jlLabelNamaCust = new javax.swing.JLabel();
        garis6 = new javax.swing.JLabel();
        ttlCust = new javax.swing.JLabel();
        jLabelTtlCust = new javax.swing.JLabel();
        garis7 = new javax.swing.JLabel();
        jenisKelCust = new javax.swing.JLabel();
        jLabelJenisKelCust = new javax.swing.JLabel();
        garis8 = new javax.swing.JLabel();
        alamatCust = new javax.swing.JLabel();
        jLabelAlamatCust = new javax.swing.JLabel();
        garis9 = new javax.swing.JLabel();
        pekerjaanCust = new javax.swing.JLabel();
        jLabelPekerjaanCust = new javax.swing.JLabel();
        garis10 = new javax.swing.JLabel();
        noHpCust = new javax.swing.JLabel();
        jLabelNoHpCust = new javax.swing.JLabel();
        garis11 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jTfJumHari = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jBtnTotalHarga = new javax.swing.JButton();
        jBtnTambahTrans = new javax.swing.JButton();
        jBtnIdMot = new javax.swing.JButton();
        jBtnIdCust = new javax.swing.JButton();
        btnExit1 = new javax.swing.JLabel();
        jLabelTotalHarga = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        garis12 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jTfIdTrans = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(250, 350));
        setUndecorated(true);
        setResizable(false);

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Detile Motor");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, -1, -1));

        idMot.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        idMot.setText("Id Motor :");
        jPanel1.add(idMot, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, -1));

        jLabelIdMot.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jPanel1.add(jLabelIdMot, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 200, 30));

        garis.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        garis.setText("_______________________________________");
        jPanel1.add(garis, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 190, 30));

        jenisMot.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jenisMot.setText("Jenis Motor :");
        jPanel1.add(jenisMot, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, -1, -1));

        jLabelJenisMot.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jPanel1.add(jLabelJenisMot, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 200, 30));

        garis1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        garis1.setText("_______________________________________");
        jPanel1.add(garis1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 190, 30));

        tipeMot.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tipeMot.setText("Tipe :");
        jPanel1.add(tipeMot, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, -1, -1));

        jLabelTipeMot.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jPanel1.add(jLabelTipeMot, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 200, 30));

        garis2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        garis2.setText("_______________________________________");
        jPanel1.add(garis2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 190, 30));

        warnaMot.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        warnaMot.setText("Warna :");
        jPanel1.add(warnaMot, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, -1, -1));

        jLabelWarnaMot.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jPanel1.add(jLabelWarnaMot, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, 200, 30));

        garis3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        garis3.setText("_______________________________________");
        jPanel1.add(garis3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, 190, 30));

        hargaMot.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        hargaMot.setText("Harga :");
        jPanel1.add(hargaMot, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, -1, -1));

        jLabelHargaMot.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jPanel1.add(jLabelHargaMot, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, 200, 30));

        garis4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        garis4.setText("_______________________________________");
        jPanel1.add(garis4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 380, 190, 30));
        jPanel1.add(jLabelStokUnit, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 450, 20, 20));
        jPanel1.add(jLabelStokUnitKur, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 450, 20, 20));
        jPanel1.add(jLabelStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 510, 20, 20));

        jPanel3.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(9, 5, 255, 600));

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Detile Customer");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, -1, -1));

        idCust.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        idCust.setText("Id Customer :");
        jPanel2.add(idCust, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, -1));

        jLabelIdCust.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jPanel2.add(jLabelIdCust, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 200, 30));

        garis5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        garis5.setText("_______________________________________");
        jPanel2.add(garis5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 190, 30));

        namaCust.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        namaCust.setText("Nama :");
        jPanel2.add(namaCust, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, -1, -1));

        jlLabelNamaCust.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jPanel2.add(jlLabelNamaCust, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 200, 30));

        garis6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        garis6.setText("_______________________________________");
        jPanel2.add(garis6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 190, 30));

        ttlCust.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ttlCust.setText("TTL :");
        jPanel2.add(ttlCust, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, -1, -1));

        jLabelTtlCust.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jPanel2.add(jLabelTtlCust, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 200, 30));

        garis7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        garis7.setText("_______________________________________");
        jPanel2.add(garis7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 190, 30));

        jenisKelCust.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jenisKelCust.setText("Jenis Kelamin :");
        jPanel2.add(jenisKelCust, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, -1, -1));

        jLabelJenisKelCust.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jPanel2.add(jLabelJenisKelCust, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, 200, 30));

        garis8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        garis8.setText("_______________________________________");
        jPanel2.add(garis8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, 190, 30));

        alamatCust.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        alamatCust.setText("Alamat :");
        jPanel2.add(alamatCust, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, -1, -1));

        jLabelAlamatCust.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jPanel2.add(jLabelAlamatCust, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, 200, 30));

        garis9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        garis9.setText("_______________________________________");
        jPanel2.add(garis9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 380, 190, 30));

        pekerjaanCust.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        pekerjaanCust.setText("Pekerjaan :");
        jPanel2.add(pekerjaanCust, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 410, -1, -1));

        jLabelPekerjaanCust.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jPanel2.add(jLabelPekerjaanCust, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 430, 200, 30));

        garis10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        garis10.setText("_______________________________________");
        jPanel2.add(garis10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 440, 190, 30));

        noHpCust.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        noHpCust.setText("No Hp :");
        jPanel2.add(noHpCust, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 470, -1, -1));

        jLabelNoHpCust.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jPanel2.add(jLabelNoHpCust, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 490, 200, 30));

        garis11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        garis11.setText("_______________________________________");
        jPanel2.add(garis11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 500, 190, 30));

        jPanel3.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(282, 5, 255, 600));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel15.setText("TRANSAKSI");
        jPanel3.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 20, -1, -1));
        jPanel3.add(jTfJumHari, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 230, 160, 30));

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel20.setText("Jumlah Hari");
        jPanel3.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 210, -1, -1));

        jBtnTotalHarga.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jBtnTotalHarga.setText("Total Harga");
        jBtnTotalHarga.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnTotalHargaMouseClicked(evt);
            }
        });
        jBtnTotalHarga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnTotalHargaActionPerformed(evt);
            }
        });
        jPanel3.add(jBtnTotalHarga, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 280, 120, 34));

        jBtnTambahTrans.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jBtnTambahTrans.setText("Tambah Transaksi");
        jBtnTambahTrans.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnTambahTransMouseClicked(evt);
            }
        });
        jPanel3.add(jBtnTambahTrans, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 540, 140, 34));

        jBtnIdMot.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jBtnIdMot.setText("Id Motor");
        jBtnIdMot.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnIdMotMouseClicked(evt);
            }
        });
        jPanel3.add(jBtnIdMot, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 130, 160, 30));

        jBtnIdCust.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jBtnIdCust.setText("Id Customer");
        jBtnIdCust.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnIdCustMouseClicked(evt);
            }
        });
        jPanel3.add(jBtnIdCust, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 170, 160, 30));

        btnExit1.setIcon(new javax.swing.ImageIcon("D:\\eza\\semester 5\\2. Pemrograman Visual\\UAS\\Icon\\closeBtn.png")); // NOI18N
        btnExit1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnExit1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnExit1MouseClicked(evt);
            }
        });
        jPanel3.add(btnExit1, new org.netbeans.lib.awtextra.AbsoluteConstraints(738, 5, -1, -1));

        jLabelTotalHarga.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jPanel3.add(jLabelTotalHarga, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 330, 180, 30));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("Rp.");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 330, -1, 30));

        garis12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        garis12.setText("____________________________________");
        jPanel3.add(garis12, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 340, 180, 40));

        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel21.setText("Id Transaksi");
        jPanel3.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 70, -1, -1));
        jPanel3.add(jTfIdTrans, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 90, 160, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 11, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 11, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnTotalHargaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnTotalHargaMouseClicked
        int harga,hari,hasil;
        harga = Integer.parseInt(jLabelHargaMot.getText());
        hari = Integer.parseInt(jTfJumHari.getText());
        hasil = harga * hari;
        
        jLabelTotalHarga.setText(String.valueOf(hasil));
        jLabelStatus.setText("Pinjam");
    }//GEN-LAST:event_jBtnTotalHargaMouseClicked

    private void jBtnIdMotMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnIdMotMouseClicked
        FormMotor newFormMot = new FormMotor();
        newFormMot.setVisible(true);
    }//GEN-LAST:event_jBtnIdMotMouseClicked

    private void jBtnIdCustMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnIdCustMouseClicked
        FormCust newFormCust = new FormCust();
        newFormCust.setVisible(true);
    }//GEN-LAST:event_jBtnIdCustMouseClicked

    private void btnExit1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExit1MouseClicked
        this.dispose();
    }//GEN-LAST:event_btnExit1MouseClicked

    private void jBtnTotalHargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnTotalHargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnTotalHargaActionPerformed

    private void jBtnTambahTransMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnTambahTransMouseClicked
        insertTrans();
        updateStok();
        updateStokTransTable();
        DashAdmin.loadDetileTrans();
        
    }//GEN-LAST:event_jBtnTambahTransMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Transaksi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel alamatCust;
    private javax.swing.JLabel btnExit1;
    private javax.swing.JLabel garis;
    private javax.swing.JLabel garis1;
    private javax.swing.JLabel garis10;
    private javax.swing.JLabel garis11;
    private javax.swing.JLabel garis12;
    private javax.swing.JLabel garis2;
    private javax.swing.JLabel garis3;
    private javax.swing.JLabel garis4;
    private javax.swing.JLabel garis5;
    private javax.swing.JLabel garis6;
    private javax.swing.JLabel garis7;
    private javax.swing.JLabel garis8;
    private javax.swing.JLabel garis9;
    private javax.swing.JLabel hargaMot;
    private javax.swing.JLabel idCust;
    private javax.swing.JLabel idMot;
    private javax.swing.JButton jBtnIdCust;
    private javax.swing.JButton jBtnIdMot;
    private javax.swing.JButton jBtnTambahTrans;
    private javax.swing.JButton jBtnTotalHarga;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel4;
    public static javax.swing.JLabel jLabelAlamatCust;
    public static javax.swing.JLabel jLabelHargaMot;
    public static javax.swing.JLabel jLabelIdCust;
    public static javax.swing.JLabel jLabelIdMot;
    public static javax.swing.JLabel jLabelJenisKelCust;
    public static javax.swing.JLabel jLabelJenisMot;
    public static javax.swing.JLabel jLabelNoHpCust;
    public static javax.swing.JLabel jLabelPekerjaanCust;
    private javax.swing.JLabel jLabelStatus;
    public static javax.swing.JLabel jLabelStokUnit;
    public static javax.swing.JLabel jLabelStokUnitKur;
    public static javax.swing.JLabel jLabelTipeMot;
    private javax.swing.JLabel jLabelTotalHarga;
    public static javax.swing.JLabel jLabelTtlCust;
    public static javax.swing.JLabel jLabelWarnaMot;
    public static javax.swing.JPanel jPanel1;
    public static javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jTfIdTrans;
    private javax.swing.JTextField jTfJumHari;
    private javax.swing.JLabel jenisKelCust;
    private javax.swing.JLabel jenisMot;
    public static javax.swing.JLabel jlLabelNamaCust;
    private javax.swing.JLabel namaCust;
    private javax.swing.JLabel noHpCust;
    private javax.swing.JLabel pekerjaanCust;
    private javax.swing.JLabel tipeMot;
    private javax.swing.JLabel ttlCust;
    private javax.swing.JLabel warnaMot;
    // End of variables declaration//GEN-END:variables
}
